---
name: Data Platform Support Request
description: Request support from the Data Platform team
title: "Title of your issue"
labels: ["ap-support", "triage"]
assignees:
  - moj-data-platform-robot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this support request form. Please fill out the sections below and we will get back to you as soon as possible. Please note that this is a public repository, so _do not include any sensitive information_.
  - type: checkboxes
    id: acknowledge
    attributes:
      label: Acknowledgements
      options:
        - label: I have searched the [user guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html) and cannot find a solution.
          required: true
        - label: I have searched for a similar [issue](https://github.com/ministryofjustice/data-platform-support/issues) and cannot find one.
          required: true
        - label: I acknowledge that the Data Platform Apps and Tools team are not responsible for the _application code_ deployed on the Cloud Platform and this is the responsibility of the application owner. I have already contacted the application owner and they have confirmed that this is not an application issue.
          required: true
        - label: I have not included sensitive information in this request.
          required: true
  - type: dropdown
    id: tool
    attributes:
      label: Which tool do you need help with?
      multiple: true
      options:
        - Amazon Web Services
        - Application Migration Support
        - Auth0
        - Control Panel
        - Database Access
        - JupyterLab
        - RStudio
        - S3
        - User and Account
        - Not applicable
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what you see, but don't include any sensitive information.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Please include a screenshot. This will help us to understand the issue.
  - type: checkboxes
    id: logs
    attributes:
      label: Logs 
      options:
        - label: I have searched the [logs](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/rshiny-app.html#kibana-on-cloud-platform) which are provided below.
          required: true
  - type: textarea
    id: logs-output
    attributes:
      label: Logs Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
  - type: textarea
    attributes:
      label: Logs Hyperlink
      description: Please add a hyperlink to any referenced logs below.
