---
name: Data Platform Support Request
description: Request support from the Data Platform team
title: "Title of your issue"
labels: ["ap-support", "triage"]
assignees:
  - moj-data-platform-robot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this support request form. Please fill out the sections below and we will get back to you as soon as possible. Please note that this is a public repository, so _do not include any sensitive information_.
  - type: checkboxes
    id: acknowledge
    attributes:
      label: Acknowledgements
      options:
        - label: I have searched the [user guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html) and cannot find a solution.
          required: true
        - label: I have searched for a similar [issue](https://github.com/ministryofjustice/data-platform-support/issues) and cannot find one.
          required: true
        - label: I acknowledge that the Data Platform Apps and Tools team are not responsible for the _application code_ deployed on the Data Platform and this is the responsibility of the application owner. I have already contacted the application owner and they have confirmed that this is not an application issue.
          required: true
  - type: dropdown
    id: tool
    attributes:
      label: Which tool do you need help with?
      multiple: true
      options:
        - Amazon Web Services
        - Application Migration Support
        - Auth0
        - Control Panel
        - Database Access
        - JupyterLab
        - RStudio
        - S3
        - User and Account
        - Not applicable
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see, but don't include any sensitive information
    validations:
      required: true
  - type: checkboxes
    id: logs
    attributes:
      label: Logs
      options:
        - label: I have searched the [logs](https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html) which are provided below.
          required: true
  - type: textarea
    id: logs-output
    attributes:
      label: Log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: Copy relevant log output here.
      render: bash
  - type: textarea
    attributes:
      label: Log hyperlink
      description: A hyperlink to the location of the logs. 
      placeholder: Please add a hyperlink to any referenced logs.
