name: 🤝 Transfer
description: Raise a request to onboard to the Transfer Service.
title: " 🤝 <title>"
labels: ["triage", "transfer-access-request"]
body:
  - type: input
    id: supplier-name
    attributes:
      label: Supplier Name
      value:
    validations:
      required: true
  - type: input
    id: supplier-email
    attributes:
      label: Supplier Email
      description: Please provide the email address of the supplier.
      value:
    validations:
      required: true
  - type: input
    id: supplier-ip
    attributes:
      label: Supplier IP Address
      description: Please provide the IP address of the supplier's server.
      value:
    validations:
      required: true
  - type: input
    id: supplier-key
    attributes:
      label: Supplier SSH Key
      description: Please provide the public key for the supplier's SSH key. Information on how to generate a public key can be found [here](https://git-scm.com/book/en/v2/Git-on-the-Server-Generating-Your-SSH-Public-Key.).
      value:
    validations:
      required: true
  - type: input
    id: supplier-target-location
    attributes:
      label: Supplier Target Location
      description: Specify the target location where the data will be transferred (e.g. `s3://${TARGET_BUCKET}/${OPTIONAL_PREFIX}`).
      value:
    validations:
      required: true