name: Slack Notification Test

on:
  push:
    branches:
      - main

jobs:
  test-slack-notification:
    name: Test Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Force Failure
        id: force_failure
        run: |
          echo "This step will fail"
          exit 1

      - name: Notify Slack on Failure
        if: failure()
        id: slack_notification
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
        with:
          payload: |
            {
              "run_id": "${{ github.run_id }}",
              "pull_request": "${{ github.event.pull_request.html_url }}",
              "event_number": "${{ github.event.number }}",
              "ref": "${{ github.ref }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
